--
-- PostgreSQL database dump
--

\restrict PLkI2A2anCPiDcxpWsxXIGpkxXDLhv0AUMse1oKpl5SPfMjpptYvHc4vjpgl9wF

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campushub_department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_department (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20)
);


ALTER TABLE public.campushub_department OWNER TO postgres;

--
-- Name: accounts_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.campushub_accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    department_id bigint,
    role character varying(100) NOT NULL
);


ALTER TABLE public.campushub_accounts_user OWNER TO postgres;

--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.campushub_accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_facility; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_facility (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text NOT NULL,
    capacity integer NOT NULL,
    rate numeric(10,2) NOT NULL,
    price_type character varying(20) NOT NULL,
    mode character varying(20) NOT NULL,
    room_type character varying(120) NOT NULL,
    amenities jsonb NOT NULL,
    status character varying(20) NOT NULL,
    slots character varying(120) NOT NULL,
    image_url character varying(200) NOT NULL,
    bookings integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    CONSTRAINT api_facility_bookings_check CHECK ((bookings >= 0)),
    CONSTRAINT api_facility_capacity_check CHECK ((capacity >= 0))
);


ALTER TABLE public.api_facility OWNER TO postgres;

--
-- Name: api_facility_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_facility ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_facility_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_gmail_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_gmail_config (
    id bigint NOT NULL,
    gmail_user character varying(254) NOT NULL,
    gmail_app_password character varying(128) NOT NULL,
    smtp_host character varying(120) NOT NULL,
    smtp_port integer NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT api_gmailconfig_smtp_port_check CHECK ((smtp_port >= 0))
);


ALTER TABLE public.campushub_gmail_config OWNER TO postgres;

--
-- Name: api_gmailconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_gmail_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_gmailconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_orders (
    id bigint NOT NULL,
    buyer_user_id integer,
    buyer_name character varying(150) NOT NULL,
    buyer_email character varying(254) NOT NULL,
    product_name character varying(150) NOT NULL,
    category character varying(80) NOT NULL,
    seller_name character varying(150) NOT NULL,
    seller_contact character varying(180) NOT NULL,
    option character varying(40) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    image_url text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint,
    CONSTRAINT api_marketplaceorder_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.campushub_orders OWNER TO postgres;

--
-- Name: api_marketplaceorder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_marketplaceorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_password_reset_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_password_reset_code (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code_hash character varying(128) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.campushub_password_reset_code OWNER TO postgres;

--
-- Name: api_passwordresetcode_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_password_reset_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_passwordresetcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_product (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text NOT NULL,
    category character varying(80) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    image_url text NOT NULL,
    approval_status character varying(20) NOT NULL,
    rejection_reason text NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approved_at timestamp with time zone,
    approved_by_id bigint,
    seller_id bigint NOT NULL,
    CONSTRAINT api_product_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.campushub_product OWNER TO postgres;

--
-- Name: api_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_product_interaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_product_interaction (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    interaction_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.campushub_product_interaction OWNER TO postgres;

--
-- Name: api_productinteraction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_product_interaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_productinteraction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_seller_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_seller_request (
    id bigint NOT NULL,
    student_id character varying(50) NOT NULL,
    full_name character varying(150) NOT NULL,
    course_section character varying(120) NOT NULL,
    contact_number character varying(40) NOT NULL,
    product_type character varying(120) NOT NULL,
    message text NOT NULL,
    status character varying(20) NOT NULL,
    reviewed_at timestamp with time zone,
    rejection_reason text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reviewed_by_id bigint,
    user_id bigint
);


ALTER TABLE public.campushub_seller_request OWNER TO postgres;

--
-- Name: api_sellerrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campushub_seller_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_sellerrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campushub_facility; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_facility (
    id character varying(30) NOT NULL,
    facility_name character varying(150) NOT NULL,
    description text,
    capacity integer DEFAULT 0,
    rate numeric(10,2) DEFAULT 0,
    price_type character varying(20) DEFAULT 'hour'::character varying,
    booking_mode character varying(20) DEFAULT 'room'::character varying,
    rooms_units integer,
    room_type character varying(120),
    amenities jsonb DEFAULT '[]'::jsonb,
    slots character varying(120),
    image_url text,
    availability_status character varying(20) DEFAULT 'available'::character varying,
    created_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.campushub_facility OWNER TO postgres;

--
-- Name: campushub_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_role (
    id uuid NOT NULL,
    role_name character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.campushub_role OWNER TO postgres;

--
-- Name: campushub_rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_rooms (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    facility_id character varying(30) NOT NULL,
    room_name character varying(150),
    descriptions text,
    capacity integer DEFAULT 0,
    price numeric(10,2) DEFAULT 0,
    available_status character varying(20) DEFAULT 'available'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.campushub_rooms OWNER TO postgres;

--
-- Name: campushub_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campushub_user (
    id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(150) NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.campushub_user OWNER TO postgres;

--
-- Name: campushub_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.campushub_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.campushub_user_id_seq OWNER TO postgres;

--
-- Name: campushub_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.campushub_user_id_seq OWNED BY public.campushub_user.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: campushub_user id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_user ALTER COLUMN id SET DEFAULT nextval('public.campushub_user_id_seq'::regclass);


--
-- Data for Name: api_facility; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_facility (id, name, description, capacity, rate, price_type, mode, room_type, amenities, status, slots, image_url, bookings, created_at, updated_at, created_by_id) FROM stdin;
1	cc	trgfdfgdfgdfg	65	4000.00	night	slot	Standard Room	["Comfort Room"]	available	awdasdsdasd	blob:http://127.0.0.1:8000/8c0c470b-7fd5-48b0-82b8-f8f6423c568b	0	2026-05-24 17:37:06.1936+00	2026-05-24 17:37:06.193615+00	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add product	6	add_product
22	Can change product	6	change_product
23	Can delete product	6	delete_product
24	Can view product	6	view_product
25	Can view seller products	6	can_view_seller_products
26	Can approve seller products	6	can_approve_seller_products
27	Can add seller request	7	add_sellerrequest
28	Can change seller request	7	change_sellerrequest
29	Can delete seller request	7	delete_sellerrequest
30	Can view seller request	7	view_sellerrequest
31	Can view seller requests	7	can_view_seller_requests
32	Can approve seller requests	7	can_approve_seller_requests
33	Can add department	8	add_department
34	Can change department	8	change_department
35	Can delete department	8	delete_department
36	Can view department	8	view_department
37	Can add user	10	add_user
38	Can change user	10	change_user
39	Can delete user	10	delete_user
40	Can view user	10	view_user
41	Can add User Role	9	add_role
42	Can change User Role	9	change_role
43	Can delete User Role	9	delete_role
44	Can view User Role	9	view_role
45	Can access Products	9	can_access_products
46	Can access Orders	9	can_access_orders
47	Can access User Management	9	can_access_user_management
48	Can access Facilities	9	can_access_facilities
49	Can access Reports	9	can_access_reports
50	Can add campus hub user	11	add_campushubuser
51	Can change campus hub user	11	change_campushubuser
52	Can delete campus hub user	11	delete_campushubuser
53	Can view campus hub user	11	view_campushubuser
54	Can add facility	12	add_facility
55	Can change facility	12	change_facility
56	Can delete facility	12	delete_facility
57	Can view facility	12	view_facility
58	Can manage facilities	12	can_manage_facilities
59	Can add password reset code	14	add_passwordresetcode
60	Can change password reset code	14	change_passwordresetcode
61	Can delete password reset code	14	delete_passwordresetcode
62	Can view password reset code	14	view_passwordresetcode
63	Can add product interaction	15	add_productinteraction
64	Can change product interaction	15	change_productinteraction
65	Can delete product interaction	15	delete_productinteraction
66	Can view product interaction	15	view_productinteraction
67	Can add Gmail configuration	13	add_gmailconfig
68	Can change Gmail configuration	13	change_gmailconfig
69	Can delete Gmail configuration	13	delete_gmailconfig
70	Can view Gmail configuration	13	view_gmailconfig
71	Can add marketplace order	16	add_marketplaceorder
72	Can change marketplace order	16	change_marketplaceorder
73	Can delete marketplace order	16	delete_marketplaceorder
74	Can view marketplace order	16	view_marketplaceorder
75	Can add room	17	add_room
76	Can change room	17	change_room
77	Can delete room	17	delete_room
78	Can view room	17	view_room
\.


--
-- Data for Name: campushub_accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, department_id, role) FROM stdin;
2	pbkdf2_sha256$1200000$HF3jGX4NxR3XNuVwqXGvdd$t2YTM2WamP9Q4sQrOu5rWhTCXPwrpLNnnpFvQAZsTCo=	2026-05-29 15:25:22.400378+00	f	MarketPlaceAdmin2026	Marketplace	Admin	marketplaceadmin2026@campushub.local	t	t	2026-05-16 16:17:59+00	1	Marketplace Admin
5	pbkdf2_sha256$1200000$eZjQJUXmXMBL9WpebA7CII$clRMtMi+Qk4G/tAzLBTOdgrtAjCV1xisgWMRqrFU9CI=	\N	f	momomo@3443	momo	bubu	lesterbulay19@gmail.com	f	t	2026-05-30 01:41:32.204912+00	1	Marketplace Admin
1	pbkdf2_sha256$1200000$GLszKr9dV909OUpDpw0X3d$sIjK2mJmo3dzwJec2j19mQdI6MG+9DtbX6BLdaEJ1Mk=	2026-05-30 02:05:16.52725+00	t	CampusHubAdmin2026	Super	Admin	campushubadmin2026@campushub.local	t	t	2026-05-16 16:06:38.732207+00	\N	User
\.


--
-- Data for Name: campushub_accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: campushub_accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	32
2	2	45
3	2	46
4	2	25
5	2	26
6	2	31
\.


--
-- Data for Name: campushub_department; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_department (id, name, code) FROM stdin;
1	Bachelor of Food Processing and Technology	BFPT
2	Bachelor of Technology Livelihood Education Major in Home Economics	BTLED-HE
3	Bachelor of Information Technology	BSIT
\.


--
-- Data for Name: campushub_facility; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_facility (id, facility_name, description, capacity, rate, price_type, booking_mode, rooms_units, room_type, amenities, slots, image_url, availability_status, created_by, created_at, updated_at) FROM stdin;
CAMFACIL202605263404	Covered Court	awdsasadsasewads	250	4000.00	session	slot	\N	Standard Room	["Comfort Room"]	Slot	/media/upload/facilities/covered_court_CAMFACIL202605263404.jpg	available	\N	2026-05-26 03:10:37.025746	2026-05-26 07:10:42.348414
\.


--
-- Data for Name: campushub_gmail_config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_gmail_config (id, gmail_user, gmail_app_password, smtp_host, smtp_port, is_active, updated_at) FROM stdin;
\.


--
-- Data for Name: campushub_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_orders (id, buyer_user_id, buyer_name, buyer_email, product_name, category, seller_name, seller_contact, option, quantity, unit_price, total_price, image_url, status, created_at, product_id) FROM stdin;
1	7	Lester Bulay	lesterbulay@gmail.com	CocaCola	Beverages	CampusHub Admin	campushubadmin2026@campushub.local	Pickup	1	20.00	20.00	http://192.168.137.61:8000/api/products/7/image/	pending	2026-05-26 08:21:21.285983+00	\N
\.


--
-- Data for Name: campushub_password_reset_code; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_password_reset_code (id, email, code_hash, expires_at, used, created_at) FROM stdin;
1	lesterbulay@gmail.com	pbkdf2_sha256$1200000$m81H25DSezE8NJjTwoOmUs$6byPvgsQu2zjFWECBVKkKzgnE1ZbEgU2ulpba5Ss7U8=	2026-05-26 06:31:36.039416+00	t	2026-05-26 06:16:36.039709+00
2	lesterbulay@gmail.com	pbkdf2_sha256$1200000$3amR0F5haeeDjKARp6pP2r$Y0N3Qnj2+mUNI+dPPPix9fsztONlnMIRzesCvkkECx0=	2026-05-26 06:43:22.647922+00	t	2026-05-26 06:28:22.648381+00
3	lesterbulay@gmail.com	pbkdf2_sha256$1200000$0XorQlBfH8d7NtTMFznE3J$HYXpkRBnaDYJH8gv8DV02CrDrmgNLRWI3WQ3Ne5IJTc=	2026-05-26 06:43:44.682864+00	t	2026-05-26 06:28:44.683134+00
4	lesterbulay@gmail.com	pbkdf2_sha256$1200000$plltxVMpMMFiop0KStoXjP$8WC0n/xhvd3jUZNZvOhPWGzuJG673NsV915DlXIMIYA=	2026-05-26 06:46:20.572439+00	t	2026-05-26 06:31:20.572687+00
5	lesterbulay@gmail.com	pbkdf2_sha256$1200000$EHdgSAwqNFoTaawPEmsMJM$gIjBIKUKNRK1CG92YvToR6aKaccQUcHmBv5jrKfZFwk=	2026-05-26 06:53:52.826352+00	t	2026-05-26 06:38:52.826621+00
6	lesterbulay@gmail.com	pbkdf2_sha256$1200000$AlLwTukYQ6kkMS2222AF95$IB0KYmpY0Hcdydm7SjlQrHxuAmEodzSCQRGfjENtoJo=	2026-05-26 06:57:35.627191+00	t	2026-05-26 06:42:35.627397+00
\.


--
-- Data for Name: campushub_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_product (id, name, description, category, price, stock, image_url, approval_status, rejection_reason, submitted_at, updated_at, approved_at, approved_by_id, seller_id) FROM stdin;
16	BananaCue	adwasadasdadwasdasda	Snacks	10.00	27	/media/upload/products/bananacue_16.png	approved		2026-05-29 02:06:26.448224+00	2026-05-29 02:06:26.48774+00	2026-05-29 02:06:26.44479+00	1	1
17	KamoteCue	dasadas	Snacks	10.00	24	/media/upload/products/kamotecue_17.jpg	approved		2026-05-29 12:04:07.610303+00	2026-05-29 12:04:07.712572+00	2026-05-29 12:04:07.602145+00	1	1
\.


--
-- Data for Name: campushub_product_interaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_product_interaction (id, user_id, interaction_type, created_at, product_id) FROM stdin;
69	7	view	2026-05-29 09:54:01.424866+00	16
70	7	view	2026-05-29 09:54:01.789111+00	16
71	7	view	2026-05-29 09:54:07.29251+00	16
\.


--
-- Data for Name: campushub_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_role (id, role_name, description, created_at) FROM stdin;
cc4c1223-e2f3-4fb3-8ae0-43c7ebac2fb0	Marketplace Admin	Manage marketplace products and orders.	2026-05-16 16:01:58.974978+00
67b4c9a3-51b7-4fcf-bbc6-8e60fbe6e8d2	Facility Admin	Manage facilities and bookings.	2026-05-16 16:01:58.976328+00
4f801c87-9a18-4fd3-8d09-eee01d5f0617	User	Default basic application access.	2026-05-16 16:01:58.978206+00
\.


--
-- Data for Name: campushub_rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_rooms (id, facility_id, room_name, descriptions, capacity, price, available_status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: campushub_seller_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_seller_request (id, student_id, full_name, course_section, contact_number, product_type, message, status, reviewed_at, rejection_reason, created_at, updated_at, reviewed_by_id, user_id) FROM stdin;
\.


--
-- Data for Name: campushub_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campushub_user (id, first_name, last_name, username, email, password_hash, created_at, updated_at) FROM stdin;
5	gyff	fttff	ggffhf	gyfg@gmail.com	pbkdf2_sha256$1200000$bE3CCzQvRlpbIW9sK3UkNV$5i0Lsvr07ZxhFBuPKsk0x2yARdI9wquZmh8R5KFujgc=	2026-05-22 07:13:55.376531	2026-05-22 07:13:55.376556
6	Test	User	testuser123	test@test.com	pbkdf2_sha256$1200000$hFtNR3zfdv761j2pcVZl4U$NZNSDnGvUTwFVxp+nez20EfIwR/98MUERYNT+DgEa/o=	2026-05-22 07:18:51.582078	2026-05-22 07:18:51.582121
8	Jessie	Bitantos	jessie.bitantos2026	jessiebitantos@gmail.com	pbkdf2_sha256$1200000$u4cS96cqOZDR2fe8kcWGsJ$+P7PLq8G4ncVjVYzKyFe/e+8ac8vr8/2DSww7VYDZE0=	2026-05-26 05:03:03.647119	2026-05-26 05:03:03.647384
7	Lester	Bulay	Loyzkie2005	lesterbulay@gmail.com	pbkdf2_sha256$1200000$WHXztzcMYnNNZsitvQjlX2$A8pfXYqNMZrBRlFhoFRWpIcugEfmyeHNZTom/326rkA=	2026-05-24 13:45:26.348556	2026-05-26 06:45:21.227461
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-16 16:07:20.923419+00	4e5041fe-a1eb-4c4b-987e-2ad9086a19d4	Reports Admin	3		9	1
2	2026-05-16 16:07:28.045407+00	966bf345-a1b8-4b38-bac1-fde953420581	Department Admin	3		9	1
3	2026-05-16 16:17:59.87129+00	2	MarketPlaceAdmin2026	1	[{"added": {}}]	10	1
4	2026-05-16 16:18:20.467232+00	2	MarketPlaceAdmin2026	2	[{"changed": {"fields": ["Staff status"]}}]	10	1
5	2026-05-29 02:18:16.14984+00	1	Bachelor of Food Processing and Technology	1	[{"added": {}}]	8	1
6	2026-05-29 02:18:21.675923+00	1	Bachelor of Food Processing and Technology	2	[]	8	1
7	2026-05-29 02:18:54.91865+00	2	Bachelor of Technology Livelihood Education Major in Home Economics	1	[{"added": {}}]	8	1
8	2026-05-29 02:19:31.970187+00	3	Bachelor of Information Technology	1	[{"added": {}}]	8	1
9	2026-05-29 15:24:55.557771+00	2	MarketPlaceAdmin2026	2	[{"changed": {"fields": ["password"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	api	product
7	api	sellerrequest
8	accounts	department
9	accounts	role
10	accounts	user
11	api	campushubuser
12	api	facility
13	api	gmailconfig
14	api	passwordresetcode
15	api	productinteraction
16	api	marketplaceorder
17	api	room
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-16 16:01:58.807835+00
2	contenttypes	0002_remove_content_type_name	2026-05-16 16:01:58.818621+00
3	auth	0001_initial	2026-05-16 16:01:58.854984+00
4	auth	0002_alter_permission_name_max_length	2026-05-16 16:01:58.858989+00
5	auth	0003_alter_user_email_max_length	2026-05-16 16:01:58.862902+00
6	auth	0004_alter_user_username_opts	2026-05-16 16:01:58.86572+00
7	auth	0005_alter_user_last_login_null	2026-05-16 16:01:58.868191+00
8	auth	0006_require_contenttypes_0002	2026-05-16 16:01:58.868906+00
9	auth	0007_alter_validators_add_error_messages	2026-05-16 16:01:58.871533+00
10	auth	0008_alter_user_username_max_length	2026-05-16 16:01:58.874508+00
11	auth	0009_alter_user_last_name_max_length	2026-05-16 16:01:58.878821+00
12	auth	0010_alter_group_name_max_length	2026-05-16 16:01:58.883295+00
13	auth	0011_update_proxy_permissions	2026-05-16 16:01:58.885743+00
14	auth	0012_alter_user_first_name_max_length	2026-05-16 16:01:58.888153+00
15	accounts	0001_initial	2026-05-16 16:01:58.93391+00
16	accounts	0002_department_code	2026-05-16 16:01:58.940213+00
17	accounts	0003_user_role	2026-05-16 16:01:58.949119+00
18	accounts	0004_alter_user_role	2026-05-16 16:01:58.952977+00
19	accounts	0005_role_userrole	2026-05-16 16:01:58.986621+00
20	accounts	0006_remove_userrole_unique_user_role_alter_role_options_and_more	2026-05-16 16:01:58.994464+00
21	accounts	0007_alter_role_options	2026-05-16 16:01:58.997544+00
22	accounts	0008_alter_user_role	2026-05-16 16:01:59.001773+00
23	accounts	0009_alter_role_options	2026-05-16 16:01:59.002882+00
24	accounts	0010_alter_role_options	2026-05-16 16:01:59.010483+00
25	admin	0001_initial	2026-05-16 16:01:59.026349+00
26	admin	0002_logentry_remove_auto_add	2026-05-16 16:01:59.031489+00
27	admin	0003_logentry_add_action_flag_choices	2026-05-16 16:01:59.037476+00
28	api	0001_initial	2026-05-16 16:01:59.053224+00
29	api	0002_sellerrequest	2026-05-16 16:01:59.068709+00
30	sessions	0001_initial	2026-05-16 16:01:59.077166+00
31	api	0003_campushubuser_facility	2026-05-24 16:50:00.480513+00
32	api	0004_passwordresetcode_productinteraction	2026-05-26 06:15:28.592854+00
33	api	0005_gmailconfig	2026-05-26 06:15:28.604903+00
34	api	0006_product_image_url_textfield	2026-05-26 06:56:02.227155+00
35	api	0007_marketplaceorder	2026-05-26 08:19:25.141736+00
36	api	0008_rename_tables_campushub	2026-05-29 14:33:54.042776+00
37	accounts	0011_rename_all_tables_campushub	2026-05-29 14:40:59.761102+00
38	api	0009_rename_all_tables_campushub	2026-05-29 14:41:00.280954+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
w3tjeqn0p2y6g3wnqa7thyc7e5wqp424	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOIe:QDZDzNdO0U82RF6DcyfRiYyYyIhQtdqKl86ox3kskfE	2026-06-02 17:32:12.549803+00
bkefr5caxvey4i15d041i5lcl20qeri5	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOHgx:harwvL6TpY5MdGg3d5GJGmFDOZtpZyyrE6IPxJPs_YQ	2026-05-30 16:16:43.031775+00
3etceavfogidurz3w6vmljofwy3h10ea	.eJxVjDkOwjAQAP-yNbLiIz5S0vMGa2Pv4gCypTipEH9HkVJAOzOaN0TctxL3TmtcMkyg4PLLZkxPqofID6z3JlKr27rM4kjEabu4tUyv69n-DQr2AhOgxGSNyUMYnQucA-vRsrTGcjaenFSOmDjJkFgnxcRqkKxReuWtMwSfL-veOCA:1wOHkd:K4Cgt7LphbsOeNAHR_pjacIYcYQ68Wuls6untlKkcMI	2026-05-30 16:20:31.170262+00
gavnmnskq54180mu4uld5vy95k3g5mkw	.eJxVjDkOwjAQAP-yNbLiIz5S0vMGa2Pv4gCypTipEH9HkVJAOzOaN0TctxL3TmtcMkyg4PLLZkxPqofID6z3JlKr27rM4kjEabu4tUyv69n-DQr2AhOgxGSNyUMYnQucA-vRsrTGcjaenFSOmDjJkFgnxcRqkKxReuWtMwSfL-veOCA:1wOHo6:o8wFxReHOSlH7scxye8m2bac2LfdikMQweqHnzfP2kQ	2026-05-30 16:24:06.940531+00
n0jmtxg6le9igvrzfw3rl2571roi4rud	.eJxVjDkOwjAQAP-yNbLiIz5S0vMGa2Pv4gCypTipEH9HkVJAOzOaN0TctxL3TmtcMkyg4PLLZkxPqofID6z3JlKr27rM4kjEabu4tUyv69n-DQr2AhOgxGSNyUMYnQucA-vRsrTGcjaenFSOmDjJkFgnxcRqkKxReuWtMwSfL-veOCA:1wOHpg:B_o4K2Hy_oY6GP57G78g0CJE99gjGejgszV-xq2HwoA	2026-05-30 16:25:44.331607+00
f6x2r6spky0jagn6o1bjz49ledkkqpmz	.eJxVjDkOwjAQAP-yNbLiIz5S0vMGa2Pv4gCypTipEH9HkVJAOzOaN0TctxL3TmtcMkyg4PLLZkxPqofID6z3JlKr27rM4kjEabu4tUyv69n-DQr2AhOgxGSNyUMYnQucA-vRsrTGcjaenFSOmDjJkFgnxcRqkKxReuWtMwSfL-veOCA:1wOHxB:86ixFjk8-hsdpkG25t2lJ6XYDt2SCacEm0IFk-aDnto	2026-05-30 16:33:29.10583+00
awtd6d6ngwot3obfwfvxdzay3y5gjdmc	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOHxB:4lRYdJWzubF92x_xATSRtIB-N6REi2bgcsyilZfStXo	2026-05-30 16:33:29.14286+00
jh9au0mjw3fpd7ijbkhg3lyu2ym4ur1j	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOHzj:xx-FkoCwVqSix4QY3DDKFxVlpS32vpC96pSSEEySslk	2026-05-30 16:36:07.578944+00
mpn52s10dxj6squorm8kbo4pl1y3s3v0	.eJxVjDkOwjAQAP-yNbLiIz5S0vMGa2Pv4gCypTipEH9HkVJAOzOaN0TctxL3TmtcMkyg4PLLZkxPqofID6z3JlKr27rM4kjEabu4tUyv69n-DQr2AhOgxGSNyUMYnQucA-vRsrTGcjaenFSOmDjJkFgnxcRqkKxReuWtMwSfL-veOCA:1wOHzj:qAZhB7Vd8P-MVrEllgOFpjV1Wdbqaw9f-PeAOnpaMBs	2026-05-30 16:36:07.578944+00
ipw3xcc8t8h7kneq8vv61bdlktzb4jdm	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOI4i:xZ83ZvyVRN2iw2u4t8f9rRM5_73igIXa_yoiER8GjFg	2026-05-30 16:41:16.636556+00
3d458efzmlpqalv0n9qcfmvtb2ftcfp5	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOTS3:peceBl5Cg-Lx6gwW_CIUFsrcfvXg76stqS9hEiTKlps	2026-05-31 04:50:07.262228+00
b7uunysecs39e86ryhrzsg2nybympja3	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOTnl:86DibyihqjZUE8r47TYCNU1mWbvUJjLkPAoG9DwwZjI	2026-05-31 05:12:33.319601+00
hsa1z8aodko350inqo8mfs6i6ee6ku7i	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOU1l:-xnJLnDaDj85JU6GjqdeQhk7uM8xKrpVKDIs9u-xTjU	2026-05-31 05:27:01.167115+00
7f1jxkqiyk56ogcasyll0cgkkoj5wyen	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUEN:xdjbDgXykYG8t9OFCJ8jnEngP_yO3gCEwKdj3AF1YWc	2026-05-31 05:40:03.042911+00
u603joqmz9smfqy06gtc7ug2zyj04k6t	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUIF:eBvJRnrMn9LVlrroXs0LGAt13R42dVp9kTQk7b9sspM	2026-05-31 05:44:03.403269+00
75fyjrczp36pdtbk19e88b75y1bretoo	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUKj:FoOGNCU4QHGdHBXPscr1HWKBeEHjBGt_iYnN_0Lk-G0	2026-05-31 05:46:37.924463+00
3pf7wk5ixohhicwgyx4p2kpi3exwzlqk	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUUw:5PcAj1i8_E64gJDnH9qMPCctbOlXIEij0dnv_3XKtEM	2026-05-31 05:57:10.847538+00
m1xv5pzhcbrglwtl93mtyckm76at7fcm	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUe2:XxxKjsh_46CUyt8S22SEJtQFwGBBhUfl0wtGnpq80R8	2026-05-31 06:06:34.298491+00
ybr1eu0afzmmar9aolsrtpb25on1rb5u	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUiW:Ozi_Ms5KwSMr9Omt0nj_xmIPf4oMxzedtQP9nkhvBuo	2026-05-31 06:11:12.842155+00
deqin8880g331q6wlb08wrdnnzj2bsig	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUk7:v7aKWEAxOdAyTLOzhJhPFTYGQpECH4eBQtn-Zh2DKt8	2026-05-31 06:12:51.230424+00
fgxztx78qf68pyz8qvtotg14s0265i87	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUm5:ICpJGXpq7FAr93GrM5H4aMZ48vqpOd2_ajx6qE_MqDM	2026-05-31 06:14:53.732986+00
reo81acdwoo5bqdwcidil4ysmg1aehzt	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wOUq9:DJeJCLMkNzlVjtOfv9xBl1Mz1etFeS85qn8bHjCR3W8	2026-05-31 06:19:05.65496+00
8ioyqrwrur9s8vhcshwk6x60bymdtzih	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPJd9:DVglPCDuymj2Wxbklo2UJBBUVgrVwPjmdQpjg1xpNeI	2026-06-02 12:33:03.166573+00
8d91rehbnuona6hhsymgpmnegp7iixwb	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPJsz:C62XJYGQP_pNSaayakdxzLo-eJ1BT8m9fiElU0RzJM4	2026-06-02 12:49:25.839314+00
ocgbzi9bqxxdqlfzgnwop92wtqou31qd	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPK4u:Qnz6_BspUVn0GFr14Ig9EqltypiTo1tAVt0VlxpLJu0	2026-06-02 13:01:44.679761+00
xt9khsiur5hskig7yucmarx0zqhfs0zm	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKDb:Nso5toV_0YmDOrD08T3ApZ4vkXYpqR0U70mOSUz0U_c	2026-06-02 13:10:43.035944+00
osfrsy3c3ovpkomjqqhlddj7pdwfci7i	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPObO:rWBg4rjNn1r3zyoD-yB2e_lcmv4HrZrXSetTpolyCUg	2026-06-02 17:51:34.948673+00
1x1y503nndz0yowb0otgr0yr4q5efkp7	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKHI:khfGspNWs_7mEOM7F_Q1v7GIPRYrQKzh6_x9DOVal8s	2026-06-02 13:14:32.726898+00
rl91ck4uf2rs68xmspohgsntq3uhi367	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOl8:Ma_weQMohbbtLoLET5QpS1YsCnfj7c9gmyBo3adF0-Y	2026-06-02 18:01:38.517228+00
d80z6pkb1tghxju32kng9bsawb94gu5x	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKJi:z4t6SdruWF-CyRGqjPEfYAy6L0kZsmb5SPTnaf9rvuE	2026-06-02 13:17:02.4288+00
5o1yp4fwtvxuwk46ed0q0onnerokuttf	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKRH:TBuzq1H77G4nm9QY4L6UoRMFBGnc_3C-SqWxIG3LJA4	2026-06-02 13:24:51.487721+00
duixqnrqbwqhku6sl4veqbr3gb3qch14	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOnQ:88bZIR6wuuPSvazdOX7GvAbf9VqxDXSPH1qAxHSFNr0	2026-06-02 18:04:00.615204+00
8fabpih1y6uutlzewk195utm3abw20rk	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKbd:cYd3fLyUvbVWK0t_8P30CcwVS7K0KwC7UiamEOwJNFE	2026-06-02 13:35:33.549875+00
kb30kyllvahnr3kc9l2eslc1l9pib6nu	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOnq:iYiIt8qsiR500PCS7BJrMnno7vYuG7s9pGm-x2E1HC4	2026-06-02 18:04:26.95446+00
u7sqnczgxx66stit9xqkgp9cauw7i2js	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKkd:lv5iR5DGGwo-fGYvT2RRC-xRaTjjFbbxUfmwe_ikW8M	2026-06-02 13:44:51.865434+00
4jv6ohre0nn9wtvz2dy5kqnrkqpj9zay	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKpA:IRlRaramesz7HbTLi2Z399L9_vQByX8x8tCWjZWzxKU	2026-06-02 13:49:32.687696+00
2r5g2dcin1641y41o5jhb2o535pnw86w	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOu8:J43ozml_GyRroNTBaBlBO6D0E5025LcW0j-w6DVpDt4	2026-06-02 18:10:56.339923+00
zxtazz3ck2748vo01lfjiox5es7kl84m	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPKzg:WaTH4qOCazVJsl5Sgs8rLzxvmragtzIGahqSLa3X15A	2026-06-02 14:00:24.705823+00
ggmqr2j3s9jku25e95vce3budll9btz7	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPOx5:7wOkAcMKVXv97Ke7HV9f9GQzIj8RSILgb1gWA-y6ru4	2026-06-02 18:13:59.781533+00
t2b8ic6ljkt8f470mkvaezctzhm57sof	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPLAv:A6J7Oo4LFGp7y486WElXEY4Zy9l55ezhI5UkK0UtIiA	2026-06-02 14:12:01.255487+00
0kxyv4ly5ejco105n7a0p07i03ub1r2g	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPP1a:TGA43P3VLA2liaeJjgOseBMXeJX_8_vFN0qIZer1gI8	2026-06-02 18:18:38.04605+00
drkwpdcj31r6apft7w0b6oxrtqk82q9q	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPP4X:5GPh63m_2G1TP-kHcRQBgUiEh5Hp99G0WC5SOFSGhg8	2026-06-02 18:21:41.440106+00
b5sp5bmgfhdhwgwf2qnezfx79thj6bcn	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPP6o:g63p-HSuT6mQhpwdz_15-VjX3zPZeWA0O5IOOYPSyRQ	2026-06-02 18:24:02.389475+00
lo0otlz32b7n6xvwkzmaomfud8lorc17	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPP8B:1ZoLrKwWQnamgKs5DDjiyYsYxdXB9C9fjFfT-qNaz4k	2026-06-02 18:25:27.553848+00
088pbrfgx48oqpe9gx2owa7ftvclwuba	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPPCj:RTqlWUd0kGeH1gsCOgkn5jCUb2vXYCRduJoxp6L6gjk	2026-06-02 18:30:09.909476+00
dztn4j3t6zrjr0iqskillcb9kqq21u8q	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPZBC:q222F-_tCl1v-91KSl9-3HqLz5gDtEzkGX4Go1P8rGQ	2026-06-03 05:09:14.796826+00
r7pukdy0uw1i1a7k96cak0scirnd50fd	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPZDb:wD89eeV3SEv0KnaVkEFjsx2u9BEVvF_JuKtQ-cZhKVY	2026-06-03 05:11:43.545916+00
1dshdy59324f2hmgw7xud6ck7hcrwvnr	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wPfeg:3drWDkq-M18WLa-0bM1FPi5RYVap-4MBiUUAcJT1sEA	2026-06-03 12:04:06.725905+00
zuzz8pk8c89zkasktyhisa5uens761hl	.eJxVjMsOwiAQAP9lz4bwWqA9evcbyAJbqRqalPZk_HfTpAe9zkzmDZH2rca98xrnAiMYuPyyRPnJ7RDlQe2-iLy0bZ2TOBJx2i5uS-HX9Wz_BpV6hRE8e54K6myzRuPIZR2sUs4kdhwmooSoiGQxgWRW2sowhIRcUEo1BA-fL-ufN5c:1wQIu8:Uz7DaZUQqEhaR8QcH-tlurieVtinFj2SNi4-K9NGkhs	2026-06-05 05:58:40.735842+00
r120ig4ij4521y3tjkvgrfnebwnpz7ku	.eJxVjDEKwzAMAP-iuRg3OHaUsXvfYGTJqtMWB-JkCv17CWRo17vjdoi0rSVuLS9xEhjBweWXJeJXroeQJ9XHbHiu6zIlcyTmtM3cZ8nv29n-DQq1AiNcWXv2iR07m9miOvQomawPgZ232quoknQdogahIaQ8UFJPyAkR4fMFEC05Sw:1wQIwD:vFf0swC2BO4rRzqzvS66vSm6iM-emvcoNYqWj1GsSYQ	2026-06-05 06:00:49.598386+00
a9p2ggimta7rnvt2o9r7zehu2rr5zbnw	.eJxVjL0OgkAQBt9la3NB2OVYSnuegXx3eyeogYSfyvjuhoRC25nJvKnHvg39vqalH41autLllwXEZ5oOYQ9M99nFedqWMbgjcaddXTdbet3O9m8wYB2opTrXWsBKRZHN4C2zGZcWJIlqJeoBBUv0ikoiAwLlhsUbFygb-nwBA9I4Qg:1wT94e:EFRuB-x-nu_mocCI6tCjK5q52EFoo6tUNrDrz_ZbG5c	2026-06-13 02:05:16.622896+00
\.


--
-- Name: accounts_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_department_id_seq', 3, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 5, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 6, true);


--
-- Name: api_facility_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_facility_id_seq', 1, true);


--
-- Name: api_gmailconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_gmailconfig_id_seq', 1, false);


--
-- Name: api_marketplaceorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_marketplaceorder_id_seq', 1, true);


--
-- Name: api_passwordresetcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_passwordresetcode_id_seq', 6, true);


--
-- Name: api_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_product_id_seq', 17, true);


--
-- Name: api_productinteraction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_productinteraction_id_seq', 71, true);


--
-- Name: api_sellerrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_sellerrequest_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 78, true);


--
-- Name: campushub_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.campushub_user_id_seq', 8, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 9, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 38, true);


--
-- Name: campushub_department accounts_department_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_department
    ADD CONSTRAINT accounts_department_code_key UNIQUE (code);


--
-- Name: campushub_department accounts_department_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_department
    ADD CONSTRAINT accounts_department_name_key UNIQUE (name);


--
-- Name: campushub_department accounts_department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_department
    ADD CONSTRAINT accounts_department_pkey PRIMARY KEY (id);


--
-- Name: campushub_role accounts_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_role
    ADD CONSTRAINT accounts_role_pkey PRIMARY KEY (id);


--
-- Name: campushub_role accounts_role_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_role
    ADD CONSTRAINT accounts_role_role_name_key UNIQUE (role_name);


--
-- Name: campushub_accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: campushub_accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: campushub_accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: campushub_accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: campushub_accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: campushub_accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: api_facility api_facility_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_facility
    ADD CONSTRAINT api_facility_pkey PRIMARY KEY (id);


--
-- Name: campushub_gmail_config api_gmailconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_gmail_config
    ADD CONSTRAINT api_gmailconfig_pkey PRIMARY KEY (id);


--
-- Name: campushub_orders api_marketplaceorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_orders
    ADD CONSTRAINT api_marketplaceorder_pkey PRIMARY KEY (id);


--
-- Name: campushub_password_reset_code api_passwordresetcode_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_password_reset_code
    ADD CONSTRAINT api_passwordresetcode_pkey PRIMARY KEY (id);


--
-- Name: campushub_product api_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_product
    ADD CONSTRAINT api_product_pkey PRIMARY KEY (id);


--
-- Name: campushub_product_interaction api_productinteraction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_product_interaction
    ADD CONSTRAINT api_productinteraction_pkey PRIMARY KEY (id);


--
-- Name: campushub_seller_request api_sellerrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_seller_request
    ADD CONSTRAINT api_sellerrequest_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: campushub_facility campushub_facility_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_facility
    ADD CONSTRAINT campushub_facility_pkey PRIMARY KEY (id);


--
-- Name: campushub_rooms campushub_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_rooms
    ADD CONSTRAINT campushub_rooms_pkey PRIMARY KEY (id);


--
-- Name: campushub_user campushub_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_user
    ADD CONSTRAINT campushub_user_email_key UNIQUE (email);


--
-- Name: campushub_user campushub_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_user
    ADD CONSTRAINT campushub_user_pkey PRIMARY KEY (id);


--
-- Name: campushub_user campushub_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_user
    ADD CONSTRAINT campushub_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: accounts_department_code_ca047dbc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_department_code_ca047dbc_like ON public.campushub_department USING btree (code varchar_pattern_ops);


--
-- Name: accounts_department_name_24e45dbe_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_department_name_24e45dbe_like ON public.campushub_department USING btree (name varchar_pattern_ops);


--
-- Name: accounts_role_role_name_240d566f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_role_role_name_240d566f_like ON public.campushub_role USING btree (role_name varchar_pattern_ops);


--
-- Name: accounts_user_department_id_8dc06840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_department_id_8dc06840 ON public.campushub_accounts_user USING btree (department_id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.campushub_accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.campushub_accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.campushub_accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.campushub_accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.campushub_accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: api_facility_created_by_id_2fab3936; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_facility_created_by_id_2fab3936 ON public.api_facility USING btree (created_by_id);


--
-- Name: api_marketplaceorder_buyer_user_id_f3428cc7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_marketplaceorder_buyer_user_id_f3428cc7 ON public.campushub_orders USING btree (buyer_user_id);


--
-- Name: api_marketplaceorder_product_id_fd938690; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_marketplaceorder_product_id_fd938690 ON public.campushub_orders USING btree (product_id);


--
-- Name: api_passwordresetcode_email_b1713b0c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_passwordresetcode_email_b1713b0c ON public.campushub_password_reset_code USING btree (email);


--
-- Name: api_passwordresetcode_email_b1713b0c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_passwordresetcode_email_b1713b0c_like ON public.campushub_password_reset_code USING btree (email varchar_pattern_ops);


--
-- Name: api_product_approved_by_id_01f007d9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_product_approved_by_id_01f007d9 ON public.campushub_product USING btree (approved_by_id);


--
-- Name: api_product_seller_id_cb79e007; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_product_seller_id_cb79e007 ON public.campushub_product USING btree (seller_id);


--
-- Name: api_productinteraction_product_id_e1be5ed6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_productinteraction_product_id_e1be5ed6 ON public.campushub_product_interaction USING btree (product_id);


--
-- Name: api_productinteraction_user_id_fedbcc44; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_productinteraction_user_id_fedbcc44 ON public.campushub_product_interaction USING btree (user_id);


--
-- Name: api_sellerrequest_reviewed_by_id_f45159de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_sellerrequest_reviewed_by_id_f45159de ON public.campushub_seller_request USING btree (reviewed_by_id);


--
-- Name: api_sellerrequest_user_id_45b11c13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_sellerrequest_user_id_45b11c13 ON public.campushub_seller_request USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: campushub_p_user_id_12f8cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX campushub_p_user_id_12f8cf_idx ON public.campushub_product_interaction USING btree (user_id, interaction_type);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: campushub_accounts_user accounts_user_department_id_8dc06840_fk_accounts_department_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user
    ADD CONSTRAINT accounts_user_department_id_8dc06840_fk_accounts_department_id FOREIGN KEY (department_id) REFERENCES public.campushub_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_facility api_facility_created_by_id_2fab3936_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_facility
    ADD CONSTRAINT api_facility_created_by_id_2fab3936_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_orders api_marketplaceorder_product_id_fd938690_fk_api_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_orders
    ADD CONSTRAINT api_marketplaceorder_product_id_fd938690_fk_api_product_id FOREIGN KEY (product_id) REFERENCES public.campushub_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_product api_product_approved_by_id_01f007d9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_product
    ADD CONSTRAINT api_product_approved_by_id_01f007d9_fk_accounts_user_id FOREIGN KEY (approved_by_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_product api_product_seller_id_cb79e007_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_product
    ADD CONSTRAINT api_product_seller_id_cb79e007_fk_accounts_user_id FOREIGN KEY (seller_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_product_interaction api_productinteraction_product_id_e1be5ed6_fk_api_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_product_interaction
    ADD CONSTRAINT api_productinteraction_product_id_e1be5ed6_fk_api_product_id FOREIGN KEY (product_id) REFERENCES public.campushub_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_seller_request api_sellerrequest_reviewed_by_id_f45159de_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_seller_request
    ADD CONSTRAINT api_sellerrequest_reviewed_by_id_f45159de_fk_accounts_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_seller_request api_sellerrequest_user_id_45b11c13_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_seller_request
    ADD CONSTRAINT api_sellerrequest_user_id_45b11c13_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campushub_rooms campushub_rooms_facility_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campushub_rooms
    ADD CONSTRAINT campushub_rooms_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.campushub_facility(id) ON DELETE CASCADE;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.campushub_accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict PLkI2A2anCPiDcxpWsxXIGpkxXDLhv0AUMse1oKpl5SPfMjpptYvHc4vjpgl9wF

