# Generated by Django 6.0.2 on 2026-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('cashier', 'Cashier'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
