# Generated by Django 6.0.2 on 2026-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
