# Generated by Django 6.0.3 on 2026-05-14 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    default_roles = [
        ('Super Admin', 'Full access to all CampusHub modules.'),
        ('Department Admin', 'Manage department-specific records and users.'),
        ('Marketplace Admin', 'Manage marketplace products and orders.'),
        ('Facility Admin', 'Manage facilities and bookings.'),
        ('Reports Admin', 'View and generate reports.'),
        ('User', 'Default basic application access.'),
    ]

    for role_name, description in default_roles:
        Role.objects.get_or_create(
            role_name=role_name,
            defaults={'description': description},
        )


def remove_default_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(
        role_name__in=[
            'Super Admin',
            'Department Admin',
            'Marketplace Admin',
            'Facility Admin',
            'Reports Admin',
            'User',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('role_name',),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role')],
            },
        ),
        migrations.RunPython(create_default_roles, remove_default_roles),
    ]
