# Generated by Django 6.0.3 on 2026-05-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_userrole'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_name',), 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
