# Generated by Django 6.0.3 on 2026-05-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userrole_unique_user_role_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_name',), 'permissions': [('can_access_products', 'Can access Products'), ('can_access_orders', 'Can access Orders'), ('can_access_user_management', 'Can access User Management'), ('can_access_facilities', 'Can access Facilities'), ('can_access_reports', 'Can access Reports')], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
    ]
