# Generated by Django 6.0.3 on 2026-05-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_name',), 'permissions': [('can_access_products', 'Can access Products'), ('can_access_orders', 'Can access Orders'), ('can_access_user_management', 'Can access User Management'), ('can_access_facilities', 'Can access Facilities'), ('can_access_reports', 'Can access Reports'), ('can_approve_bookings', 'Can approve bookings'), ('can_manage_facilities', 'Can manage facilities'), ('can_upload_documents', 'Can upload documents'), ('can_manage_products', 'Can manage products'), ('can_manage_orders', 'Can manage orders'), ('can_access_booking', 'Can access booking'), ('can_access_marketplace', 'Can access marketplace')], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
    ]
