# Generated by Django 6.0.3 on 2026-05-16 14:57

from django.db import migrations


def remove_reverted_rbac_seed(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    extra_codenames = [
        'can_approve_bookings',
        'can_manage_facilities',
        'can_upload_documents',
        'can_manage_products',
        'can_manage_orders',
        'can_access_booking',
        'can_access_marketplace',
    ]

    Group.objects.filter(
        name__in=['Super Admin', 'Facility Admin', 'Seller', 'Student']
    ).delete()
    Permission.objects.filter(
        content_type__app_label='accounts',
        codename__in=extra_codenames,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_name',), 'permissions': [('can_access_products', 'Can access Products'), ('can_access_orders', 'Can access Orders'), ('can_access_user_management', 'Can access User Management'), ('can_access_facilities', 'Can access Facilities'), ('can_access_reports', 'Can access Reports')], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.RunPython(remove_reverted_rbac_seed, migrations.RunPython.noop),
    ]
