# Generated by Django 6.0.2 on 2026-05-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='department',
            table='campushub_department',
        ),
        migrations.AlterModelTable(
            name='role',
            table='campushub_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='campushub_accounts_user',
        ),
    ]
