# Generated by Django 6.0.2 on 2026-05-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_marketplaceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=150, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campushub_rooms',
                'ordering': ('room_name',),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': False, 'ordering': ('-created_at',)},
        ),
        migrations.RenameIndex(
            model_name='productinteraction',
            new_name='api_product_user_id_b1a5c9_idx',
            old_name='api_product_user_id_0a8f2d_idx',
        ),
        migrations.AlterModelTable(
            name='marketplaceorder',
            table='campushub_orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='campushub_product',
        ),
    ]
