# Generated by Django 6.0.2 on 2026-05-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tables_campushub'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productinteraction',
            new_name='campushub_p_user_id_12f8cf_idx',
            old_name='api_product_user_id_b1a5c9_idx',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='campushub_facility',
        ),
        migrations.AlterModelTable(
            name='gmailconfig',
            table='campushub_gmail_config',
        ),
        migrations.AlterModelTable(
            name='passwordresetcode',
            table='campushub_password_reset_code',
        ),
        migrations.AlterModelTable(
            name='productinteraction',
            table='campushub_product_interaction',
        ),
        migrations.AlterModelTable(
            name='sellerrequest',
            table='campushub_seller_request',
        ),
    ]
