# Generated by Django 6.0.3 on 2026-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_marketplace_order_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='message_to_seller',
            field=models.TextField(blank=True),
        ),
    ]
