/// Local form suggestion samples — no API.
/// Used by Autocomplete fields (product name, product type, etc.).
/// Tip: add new names to [productNames] to show them in search.
class FormSuggestionSamples {
  FormSuggestionSamples._();

  static const List<String> productNames = [
    // —— Beverages ——
    'MilkTea',
    'Brown Sugar MilkTea',
    'Taro MilkTea',
    'Matcha MilkTea',
    'Wintermelon MilkTea',
    'Okinawa MilkTea',
    'Thai Tea',
    'Milkshake',
    'Chocolate Milkshake',
    'Strawberry Milkshake',
    'Oreo Milkshake',
    'Vanilla Milkshake',
    'Iced Coffee',
    'Hot Coffee',
    'Americano',
    'Cafe Latte',
    'Cappuccino',
    'Espresso',
    'Mocha',
    'Caramel Macchiato',
    'Cold Brew',
    'Frappe',
    'Iced Tea',
    'Lemon Iced Tea',
    'Green Tea',
    'Hot Chocolate',
    'Bottled Water',
    'Mineral Water',
    'Soft Drink',
    'Cola',
    'Sprite',
    'Royal',
    'Mountain Dew',
    'Juice',
    'Orange Juice',
    'Apple Juice',
    'Mango Juice',
    'Pineapple Juice',
    'Calamansi Juice',
    'Buko Juice',
    'Sago Gulaman',
    'Fruit Shake',
    'Mango Shake',
    'Avocado Shake',
    'Smoothie',
    'Yakult',
    'Energy Drink',
    'Sports Drink',
    'Soy Milk',
    'Chocolate Drink',
    // —— Rice / silog meals ——
    'Garlic Rice',
    'Plain Rice',
    'Java Rice',
    'Tapsilog',
    'Tocilog',
    'Longsilog',
    'Hotsilog',
    'Bangsilog',
    'Chickensilog',
    'Cornsilog',
    'Spamsilog',
    'Adobo Rice',
    'Chicken Adobo',
    'Pork Adobo',
    'Sinigang Rice',
    'Kare-Kare Rice',
    'Bicol Express Rice',
    'Caldereta Rice',
    'Menudo Rice',
    'Afritada Rice',
    'Beef Steak Rice',
    'Pork Steak Rice',
    'Sisig Rice',
    'Chicken Sisig',
    'Pork Sisig',
    'Lechon Kawali Rice',
    'Crispy Pata Rice',
    'Fried Bangus Rice',
    'Tinapa Rice',
    'Daing Rice',
    'Tinola Rice',
    'Nilaga Rice',
    'Bulalo Rice',
    'Pares',
    'Beef Pares',
    'Lomi',
    'Mami',
    'Batchoy',
    'Goto',
    'Arroz Caldo',
    'Champorado',
    'Lugaw',
    'Congee',
    // —— Noodles / pasta ——
    'Pancit Canton',
    'Pancit Bihon',
    'Pancit Palabok',
    'Pancit Malabon',
    'Pancit Sotanghon',
    'Carbonara',
    'Spaghetti',
    'Filipino Spaghetti',
    'Baked Macaroni',
    'Lasagna',
    'Ramen',
    'Instant Noodles',
    'Cup Noodles',
    'Sotanghon Soup',
    'Misua',
    // —— Sandwiches / burgers ——
    'Burger',
    'Cheese Burger',
    'Chicken Burger',
    'Double Burger',
    'Hotdog',
    'Cheese Hotdog',
    'Footlong',
    'Chicken Sandwich',
    'Club Sandwich',
    'Egg Sandwich',
    'Ham Sandwich',
    'Tuna Sandwich',
    'Bacon Egg Sandwich',
    'Siopao',
    'Asado Siopao',
    'Bola-Bola Siopao',
    'Siomai',
    'Siomai Rice',
    'Pork Siomai',
    'Chicken Siomai',
    'Beef Siomai',
    'Dumplings',
    'Gyoza',
    // —— Fried / grilled ——
    'Fried Chicken',
    'Chicken Wings',
    'Chicken Nuggets',
    'Chicken Fillet',
    'Chicken Poppers',
    'Pork BBQ',
    'Chicken BBQ',
    'Isaw',
    'Betamax',
    'Adidas',
    'Fish Ball',
    'Kikiam',
    'Squid Ball',
    'Kwek-Kwek',
    'Tokneneng',
    'Calamares',
    'French Fries',
    'Cheese Fries',
    'Onion Rings',
    'Mozzarella Sticks',
    'Tempura',
    'Chicken Skin',
    'Chicharon',
    // —— Snacks / street food ——
    'Lumpia',
    'Shanghai Lumpia',
    'Vegetable Lumpia',
    'Turon',
    'Banana Cue',
    'Kamote Cue',
    'Corn on the Cob',
    'Mais',
    'Maruya',
    'Banana Chips',
    'Potato Chips',
    'Corn Chips',
    'Nachos',
    'Popcorn',
    'Crackers',
    'Biscuits',
    'Cookies',
    'Wafer',
    'Pretzels',
    'Nuts',
    'Trail Mix',
    'Candy',
    'Chocolate Bar',
    'Gummy Candy',
    'Lollipop',
    'Marshmallow',
    'Piattos',
    'Chippy',
    'Nova',
    'Boy Bawang',
    'Clover Chips',
    // —— Desserts / baked ——
    'Cupcake',
    'Donut',
    'Glazed Donut',
    'Chocolate Donut',
    'Muffin',
    'Brownie',
    'Cookie',
    'Chocolate Chip Cookie',
    'Puto',
    'Puto Bumbong',
    'Kutsinta',
    'Biko',
    'Suman',
    'Bibingka',
    'Ensaymada',
    'Pandesal',
    'Spanish Bread',
    'Cheese Bread',
    'Ube Bread',
    'Croissant',
    'Danish',
    'Cake Slice',
    'Ube Cake',
    'Chocolate Cake',
    'Cheesecake',
    'Halo-Halo',
    'Ice Cream',
    'Ice Cream Cone',
    'Sundae',
    'Fruit Salad',
    'Buko Pandan',
    'Leche Flan',
    'Maja Blanca',
    'Ginataang Bilo-Bilo',
    'Taho',
    'Yema',
    'Polvoron',
    'Pastillas',
    // —— Pizza / international ——
    'Pizza Slice',
    'Hawaiian Pizza',
    'Pepperoni Pizza',
    'Cheese Pizza',
    'Shawarma',
    'Chicken Shawarma',
    'Beef Shawarma',
    'Tacos',
    'Burrito',
    'Quesadilla',
    'Sushi Roll',
    'California Roll',
    'Kimbap',
    'Bibimbap',
    'Pad Thai',
    'Fried Rice',
    'Yang Chow Fried Rice',
    'Kimchi Fried Rice',
    'Curry Rice',
    'Chicken Curry',
    'Beef Curry',
    'Samosa',
    'Spring Rolls',
    'Waffle',
    'Pancake',
    'French Toast',
    'Omelette',
    'Scrambled Eggs',
    'Breakfast Plate',
    // —— Combos ——
    'Combo Meal A',
    'Combo Meal B',
    'Combo Meal C',
    'Student Meal',
    'Value Meal',
    'Rice Meal Combo',
    'Burger Combo',
    'Chicken Combo',
    'Snack Pack',
    'Drink + Snack',
    // —— School supplies ——
    'Notebook',
    'Ballpen',
    'Pencil',
    'Mechanical Pencil',
    'Eraser',
    'Sharpener',
    'Highlighter',
    'Marker',
    'Correction Tape',
    'Stapler',
    'Paper Clip',
    'Binder',
    'Folder',
    'Clear Book',
    'Index Card',
    'Bond Paper',
    'Intermediate Pad',
    'Yellow Pad',
    'Ruler',
    'Calculator',
    'USB Flash Drive',
    'ID Lace',
    'ID Holder',
    'Backpack',
    'Tote Bag',
    'Lunch Box',
    'Water Bottle',
    'Umbrella',
    // —— Merch / misc ——
    'School Shirt',
    'Campus Hoodie',
    'Campus Cap',
    'Lanyard',
    'Sticker Pack',
    'Keychain',
    'Tumbler',
    'Mug',
    'Phone Case',
    'Earphones',
    'Power Bank',
    'Face Mask',
    'Hand Sanitizer',
    'Tissue Pack',
    'Wet Wipes',
  ];

  static const List<String> productTypes = [
    'Food',
    'Beverages',
    'Snacks',
    'Rice Meals',
    'Desserts',
    'Combo Meals',
    'Breakfast',
    'Noodles',
    'Fast Food',
    'School Supplies',
    'Merchandise',
    'Services',
    'Electronics',
    'Apparel',
  ];

  static const List<String> categories = [
    'Rice Meals',
    'Snacks',
    'Desserts',
    'Beverages',
    'Combo Meals',
    'Breakfast',
    'School Supplies',
    'Merchandise',
  ];
}
