"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def _load_dotenv(path: Path) -> None:
    """Load KEY=VALUE pairs from a local .env file into os.environ (no overwrite)."""
    if not path.is_file():
        return
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip("'").strip('"')
            if key and key not in os.environ:
                os.environ[key] = value
    except OSError:
        pass


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k*h&!$mhhx)raetvq+!p!c$*92+4)h_6%nvi)_&9hbyu89bk(w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts permitted to access the local development server over Wi-Fi, LAN, or Android Emulator.
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "10.0.2.2",          # Android Studio Emulator (Pixel 10A / AVD) loopback to host
    "10.214.157.171",     # Current Wi-Fi LAN IP
    "192.168.1.103",
    "192.168.1.187",
    "192.168.1.169",
    "192.168.0.154",
    "192.168.56.1",
    "*",                 # Allow local development connections across any adapter or emulator
]

# Trust origins for CSRF dynamically across every local Wi-Fi, hotspot, tethering adapter, and emulator
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://10.0.2.2:8000",
    "http://10.214.157.171:8000",
    "http://192.168.1.103:8000",
    "http://192.168.1.187:8000",
    "http://192.168.1.169:8000",
    "http://192.168.0.154:8000",
    "http://192.168.56.1:8000",
]

AUTH_USER_MODEL = 'accounts.User'
# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'accounts',
    'modules.user_management.apps.UserManagementModuleConfig',
    'modules.facilities.apps.FacilitiesModuleConfig',
    'modules.marketplace.apps.MarketplaceModuleConfig',
    'modules.messages.apps.MessagesModuleConfig',
    'modules.notifications.apps.NotificationsModuleConfig',
    'modules.reports.apps.ReportsModuleConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DevHotspotCsrfMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.AdminTabAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# FastAPI chat service. Keep CHAT_JWT_SECRET identical in both services.
CHAT_JWT_SECRET = os.environ.get("CHAT_JWT_SECRET", SECRET_KEY)
CHAT_JWT_ALGORITHM = "HS256"
CHAT_TOKEN_LIFETIME_SECONDS = int(
    os.environ.get("CHAT_TOKEN_LIFETIME_SECONDS", "43200")
)
CHAT_SERVICE_HTTP_URL = os.environ.get(
    "CHAT_SERVICE_HTTP_URL", "http://127.0.0.1:8001"
).rstrip("/")
CHAT_SERVICE_WS_URL = os.environ.get(
    "CHAT_SERVICE_WS_URL", "ws://127.0.0.1:8001/ws"
)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            PROJECT_ROOT / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'campushub',
        'USER': 'postgres',
        'PASSWORD': 'CampusHub2026',
        'HOST': 'localhost',
        'PORT': '5432',

    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [PROJECT_ROOT / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = PROJECT_ROOT / 'media'

# Allow larger uploads (50MB) for product/facility images
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024

# CampusHub Gmail — credentials loaded from gmail_local.py (create from gmail_local.py.example)
try:
    from .gmail_local import (  # noqa: F401
        CAMPUSHUB_GMAIL_APP_PASSWORD,
        CAMPUSHUB_GMAIL_USER,
    )
except ImportError:
    CAMPUSHUB_GMAIL_USER = ''
    CAMPUSHUB_GMAIL_APP_PASSWORD = ''

CAMPUSHUB_SMTP_HOST = 'smtp.gmail.com'
CAMPUSHUB_SMTP_PORT = 587
CAMPUSHUB_SMTP_USE_SSL = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = CAMPUSHUB_SMTP_HOST
EMAIL_PORT = CAMPUSHUB_SMTP_PORT
EMAIL_USE_TLS = True
EMAIL_HOST_USER = CAMPUSHUB_GMAIL_USER
EMAIL_HOST_PASSWORD = CAMPUSHUB_GMAIL_APP_PASSWORD
DEFAULT_FROM_EMAIL = CAMPUSHUB_GMAIL_USER or 'noreply@campushub.local'
PASSWORD_RESET_CODE_MINUTES = 15

# Marketplace inventory automation (no per-product reorder level field)
CAMPUSHUB_LOW_STOCK_THRESHOLD = 5
CAMPUSHUB_EXPIRY_WARNING_DAYS = 7
