from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from api.views import (
    admin_login,
    admin_session_status,
    admin_archive_product,
    admin_restore_product,
    admin_delete_product,
    admin_save_product,
    admin_update_product_stock,
    approved_products,
    product_image,
    bookings_create,
    facilities_create,
    facilities_archive,
    facilities_restore,
    facilities_delete,
    facilities_list,
    facilities_update,
    marketplace_approve_product,
    marketplace_approve_seller_request,
    marketplace_reject_product,
    marketplace_reject_seller_request,
    marketplace_seller_requests,
    marketplace_orders,
    mobile_login,
    mobile_complete_profile,
    mobile_signup,
    mobile_password_reset,
    mobile_password_reset_confirm,
    mobile_password_reset_verify,
    recommended_products,
    track_product_interaction,
    seller_products_monitor,
    seller_access_request,
    seller_access_status,
    seller_submit_product,
    remove_product_background,
)
from accounts.views import (
    admin_bookings_page,
    admin_calendar_page,
    admin_facility_page,
    admin_login_page,
    admin_logout_page,
    admin_messages_page,
    admin_notifications_page,
    admin_orders_page,
    admin_order_update,
    admin_products_page,
    admin_sellers_page,
    admin_roles_page,
    admin_role_permissions_save,
    admin_roles_save,
    admin_roles_delete,
    admin_roles_status,
    admin_users_page,
    admin_users_save,
    admin_users_delete,
    admin_users_action,
    admin_user_monitoring_page,
    admin_settings_page,
    admin_backup_page,
    admin_marketplace_export_page,
    admin_marketplace_export_download,
    admin_facility_export_page,
    admin_facility_export_download,
)
from modules.reports.views import (
    admin_dashboard_page,
    admin_facility_analytics_page,
    admin_generate_reports_page,
    admin_marketplace_analytics_page,
    admin_report_download,
    admin_report_preview,
)

from modules.facilities import mobile_views as mobile_facilities

urlpatterns = [
    path("api/mobile/facilities/contact/", mobile_facilities.contact),
    path("api/mobile/facilities/<str:facility_id>/availability/", mobile_facilities.availability),
    path("api/mobile/facilities/<str:facility_id>/quote/", mobile_facilities.quote),
    path("api/mobile/bookings/", mobile_facilities.bookings),
    path("api/mobile/bookings/<str:booking_id>/", mobile_facilities.booking_detail),
    path("api/mobile/bookings/<str:booking_id>/cancel/", mobile_facilities.cancel),
    path("", admin_login_page, name="admin_login_page"),
    path("admin-logout/", admin_logout_page, name="admin_logout_page"),
    path("admin-dashboard/", admin_dashboard_page, name="admin_dashboard_page"),
    path("admin-products/", admin_products_page, name="admin_products_page"),
    path("admin-orders/", admin_orders_page, name="admin_orders_page"),
    path("admin-sellers/", admin_sellers_page, name="admin_sellers_page"),
    path(
        "admin-marketplace-analytics/",
        admin_marketplace_analytics_page,
        name="admin_marketplace_analytics_page",
    ),
    path(
        "admin-facility-analytics/",
        admin_facility_analytics_page,
        name="admin_facility_analytics_page",
    ),
    path("admin-orders/<int:order_id>/update/", admin_order_update, name="admin_order_update"),
    path("admin-messages/", admin_messages_page, name="admin_messages_page"),
    path("admin-notifications/", admin_notifications_page, name="admin_notifications_page"),
    path("admin-users/", admin_users_page, name="admin_users_page"),
    path("admin-users/save/", admin_users_save, name="admin_users_save"),
    path("admin-users/delete/", admin_users_delete, name="admin_users_delete"),
    path("admin-users/action/", admin_users_action, name="admin_users_action"),
    path("admin-roles/", admin_roles_page, name="admin_roles_page"),
    path("admin-roles/permissions/save/", admin_role_permissions_save, name="admin_role_permissions_save"),
    path("admin-roles/save/", admin_roles_save, name="admin_roles_save"),
    path("admin-roles/delete/", admin_roles_delete, name="admin_roles_delete"),
    path("admin-roles/status/", admin_roles_status, name="admin_roles_status"),
    path("admin-user-monitoring/", admin_user_monitoring_page, name="admin_user_monitoring_page"),
    path("admin-facility/", admin_facility_page, name="admin_facility_page"),
    path("admin-bookings/", admin_bookings_page, name="admin_bookings_page"),
    path("admin-calendar/", admin_calendar_page, name="admin_calendar_page"),
    path("admin-settings/", admin_settings_page, name="admin_settings_page"),
    path("admin-backup/", admin_backup_page, name="admin_backup_page"),
    path(
        "admin-export/marketplace/",
        admin_marketplace_export_page,
        name="admin_marketplace_export_page",
    ),
    path(
        "admin-export/marketplace/download/",
        admin_marketplace_export_download,
        name="admin_marketplace_export_download",
    ),
    path(
        "admin-export/facilities/",
        admin_facility_export_page,
        name="admin_facility_export_page",
    ),
    path(
        "admin-export/facilities/download/",
        admin_facility_export_download,
        name="admin_facility_export_download",
    ),
    path("admin-generate-reports/", admin_generate_reports_page, name="admin_generate_reports_page"),
    path("admin-generate-reports/preview/", admin_report_preview, name="admin_report_preview"),
    path("admin-generate-reports/download/", admin_report_download, name="admin_report_download"),
    path("admin/", admin.site.urls),
    path("api/admin_login/", admin_login, name="admin_login"),
    path("api/admin/session/", admin_session_status, name="admin_session_status"),
    path("api/chat/", include("modules.messages.urls")),
    path("api/mobile/login/", mobile_login, name="mobile_login"),
    path("api/mobile/signup/", mobile_signup, name="mobile_signup"),
    path(
        "api/mobile/profile/complete/",
        mobile_complete_profile,
        name="mobile_complete_profile",
    ),
    path("api/mobile/password-reset/", mobile_password_reset, name="mobile_password_reset"),
    path(
        "api/mobile/password-reset/verify/",
        mobile_password_reset_verify,
        name="mobile_password_reset_verify",
    ),
    path(
        "api/mobile/password-reset/confirm/",
        mobile_password_reset_confirm,
        name="mobile_password_reset_confirm",
    ),
    path("api/products/recommended/", recommended_products, name="recommended_products"),
    path(
        "api/products/interaction/",
        track_product_interaction,
        name="track_product_interaction",
    ),
    path("api/facilities/", facilities_list, name="facilities_list"),
    path("api/facilities/create/", facilities_create, name="facilities_create"),
    path("api/facilities/<str:facility_id>/update/", facilities_update, name="facilities_update"),
    path("api/facilities/<str:facility_id>/archive/", facilities_archive, name="facilities_archive"),
    path("api/facilities/<str:facility_id>/restore/", facilities_restore, name="facilities_restore"),
    path("api/facilities/<str:facility_id>/delete/", facilities_delete, name="facilities_delete"),
    path("api/bookings/create/", bookings_create, name="bookings_create"),
    path("api/products/approved/", approved_products, name="approved_products"),
    path("api/orders/", marketplace_orders, name="marketplace_orders"),
    path("api/products/<int:product_id>/image/", product_image, name="product_image"),
    path("api/products/remove-bg/", remove_product_background, name="remove_product_background"),
    path("api/products/admin/save/", admin_save_product, name="admin_save_product"),
    path("api/products/admin/<int:product_id>/stock/", admin_update_product_stock, name="admin_update_product_stock"),
    path("api/products/admin/<int:product_id>/archive/", admin_archive_product, name="admin_archive_product"),
    path("api/products/admin/<int:product_id>/restore/", admin_restore_product, name="admin_restore_product"),
    path("api/products/admin/<int:product_id>/delete/", admin_delete_product, name="admin_delete_product"),
    path("api/seller/access-request/", seller_access_request, name="seller_access_request"),
    path("api/seller/access-status/", seller_access_status, name="seller_access_status"),
    path("api/seller/products/submit/", seller_submit_product, name="seller_submit_product"),
    path("api/marketplace/products/", seller_products_monitor, name="seller_products_monitor"),
    path("api/marketplace/seller-requests/", marketplace_seller_requests, name="marketplace_seller_requests"),
    path(
        "api/marketplace/products/<int:product_id>/approve/",
        marketplace_approve_product,
        name="marketplace_approve_product",
    ),
    path(
        "api/marketplace/products/<int:product_id>/reject/",
        marketplace_reject_product,
        name="marketplace_reject_product",
    ),
    path(
        "api/marketplace/seller-requests/<int:request_id>/approve/",
        marketplace_approve_seller_request,
        name="marketplace_approve_seller_request",
    ),
    path(
        "api/marketplace/seller-requests/<int:request_id>/reject/",
        marketplace_reject_seller_request,
        name="marketplace_reject_seller_request",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
